<?php
if (!function_exists('currency_format')) {
    function currency_format($number, $suffix = 'đ') {
        if (!empty($number)) {
            return number_format($number, 0, ',', '.') . "{$suffix}";
        }
    }
}
?>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript">
    function CheckAll(parent)
    {
        var ids = document.getElementsByTagName('input');
        for(var i=0; i<ids.length; i++)
        {
            if(ids[i].name == "checkbox[]")
            {
                ids[i].checked = parent.checked;
            }
	    }
    }
</script>

<h3>BẢNG GIÁ VACXIN</h3>
<hr/>
<form>
<div>
    <table class="empty-table">
        <thead>
            <tr>
                <th>Tên Vacxin</th>
                <th>Nước Sản Xuất</th>
                <th>Giá bán lẻ</th>
                <th>Giá bán theo yêu cầu</th>
                <th>Tình trạng</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <!-- PHẦN XỬ LÝ -->
        <?php
            // Tổng số record
            $total_records = count($data);

            // Tìm limit và current page
            $limit = 10;
            $current_page = isset($_GET['page']) ? $_GET['page'] : 1;

            //  Tổng pages
            $total_page = ceil($total_records / $limit);

            // Giới hạn current_page trong khoảng 1 đến total_page
            if ($current_page > $total_page){
                $current_page = $total_page;
            }
            else if ($current_page < 1){
                $current_page = 1;
            }

            // Tìm Start
            $start = ($current_page - 1) * $limit;

            if ($total_records - $start > 10)
                $limit = $start + 10;
            else
                $limit = $total_records;

            // 
            $result = array();
            for ($i = $start; $i < $limit; $i++)
            {
                $v = new VacxinModel();
                $v = $data[$i];
                $result[] = $v;
            }
        ?>
        <!-- PHẦN HIỂN THỊ -->
        <?php
            if (count($result) > 0) 
            {
                $sn=1;
                foreach ($result as $item) 
                {
                    ?>
                        <tr>
                            <td><?php echo $item->TenVacxin; ?></td>
                            <td><?php echo $item->NuocSanXuat; ?></td>
                            <td><?php echo currency_format($item->GiaBanLe); ?></td>
                            <td><?php echo currency_format($item->GiaYeuCau); ?></td>
                            <td><?php if ($item->TinhTrang === 1) echo "Còn hàng"; else echo "Hết hàng"; ?></td>
                            <td>
                                <a href="?action=chitietvacxin&mavacxin=<?php echo $item->MaVacxin; ?>">Xem chi tiết Vacxin</a> &emsp;
                            </td>
                        <tr>

                    <?php
                }
            } 
            else { ?>
                        <tr>
                            <td colspan="8">No data found</td>
                        </tr>
                    <?php
                } 
        ?>
        </tbody>
    </table>
    <br/>
    <!-- PHẦN PHÂN TRANG -->
    <div class="paging">
        <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // HIỂN THỊ PHÂN TRANG
 
            echo '<a href="?action=banggia&page=1" style="width:50px; display:inline-block">First</a> | ';

            // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
            if ($current_page > 1 && $total_page > 1)
            {
                echo '<a href="?action=banggia&page='.($current_page-1).'" style="width:50px; display:inline-block">Prev</a> | ';
            }
 
            // Lặp khoảng giữa
            for ($i = 1; $i <= $total_page; $i++)
            {
                // Nếu là trang hiện tại thì hiển thị thẻ span
                // ngược lại hiển thị thẻ a
                if ($i == $current_page)
                {
                    echo '<span style="width:50px; display:inline-block">'.$i.'</span> | ';
                }
                else{
                    echo '<a href="?action=banggia&page='.$i.'" style="width:50px; display:inline-block">'.$i.'</a> | ';
                }
            }
 
            // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
            if ($current_page < $total_page && $total_page > 1)
            {
                echo '<a href="?action=banggia&page='.($current_page+1).'" style="width:50px; display:inline-block">Next</a> | ';
            }

            echo '<a href="?action=banggia&page='.($total_page).'" style="width:50px; display:inline-block">Last</a> | ';
        ?>
    </div>
</div>
</form>