<h2>THÔNG TIN CHI TIẾT VACXIN: <?php echo $data->TenVacxin?> </h2>
<hr/>

<form>
    <h3>1. Giới thiệu</h3>
    <p style="width: 750px;"><?php echo $data->ChiTiet?></p>
    <br/><hr/><br/>
    <h3>2. Chống chỉ định</h3>
    <p style="width: 750px;"><?php echo  $data->ChongChiDinh?></p>
    <br/><hr/><br/>
    <h3>3. Bảo quản</h3>
    <p style="width: 750px;"><?php echo $data->BaoQuan?></p>
</form>
