<script type="text/javascript">
    function check()
    {
        if (document.getElementById("MaDK").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Nhập mã phiếu đăng ký!</b></i>";
            return false;
        }

        if (document.getElementById("HoTenNguoiTiem").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Nhập họ tên người tiêm!</b></i>";
            return false;
        }

        if (document.getElementById("NgaySinh").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Nhập ngày sinh!</b></i>";
            return false;
        }

        if (document.getElementById("HoTenNguoiLienHe").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Nhập họ tên người liên hệ!</b></i>";
            return false;
        }

        if (document.getElementById("SDT").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Nhập SDT!</b></i>";
            return false;
        }

        if (document.getElementById("Vacxin").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Chọn Vacxin!</b></i>";
            return false;
        }

        if (document.getElementById("TrungTam").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Chọn Trung tâm!</b></i>";
            return false;
        }

        if (document.getElementById("NgayTiem").value  == "")
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Chọn ngày tiêm!</b></i>";
            return false;
        }

        return true;
    }
</script>

<h1>PHIẾU ĐĂNG KÝ TIÊM NGỪA TẠI TRUNG TÂM VNVC</h1>
<hr/>

 <form method ="POST" onsubmit="return check();">
 	<input type="hidden" name="action" value="dangky" />
    <table>
        <tr>
            <td>Mã phiếu đăng ký: </td>
            <td><input id="MaDK" name="MaDK" type="text" value="" /></td>
        </tr>
        <tr>
            <td>Họ tên người tiêm:</td>
            <td><input id="HoTenNguoiTiem" name="HoTenNguoiTiem" type="text" value=""/></td>                   
        </tr>
        <tr>
            <td>Ngày sinh</td>
            <td><input style="width:270px; height:30px;" id="NgaySinh" name="NgaySinh" type="date" value=""/></td>
        </tr>
        <tr>
            <td>Giới tính</td>
            <td>
                <select name="GioiTinh" class="GioiTinh" id="GioiTinh">
                    <option value='Nam'>Nam</option>
                    <option value='Nữ'>Nữ</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>Mã khách hàng (nếu có)</td>
            <td><input id="MaKH" name="MaKH" type="text" value=""/></td>
        </tr>
        <tr>
            <td>Tỉnh thành</td>
            <td><input id="TinhThanh" name="TinhThanh" type="text" value="" /></td>
        </tr> 
        <tr>
            <td>Quận huyện</td>
            <td><input id="QuanHuyen" name="QuanHuyen" type="text" value="" /></td>
        </tr> 
        <tr>
            <td>Phường xã</td>
            <td><input id="PhuongXa" name="PhuongXa" type="text" value="" /></td>
        </tr>
        <tr>
            <td>Số nhà</td>
            <td><input id="SoNha" name="SoNha" type="text" value="" /></td>
        </tr>
        <tr>
            <td>Họ tên người liên hệ</td>
            <td><input id="HoTenNguoiLienHe" name="HoTenNguoiLienHe" type="text" value="" /></td>
        </tr>   
        <tr>
            <td>Quan hệ</td>
            <td>
                <select name="QuanHe" class="QuanHe" id="QuanHe">
                    <option value='Cha'>Cha</option>
                    <option value='Mẹ'>Mẹ</option>
                    <option value='Anh/Chị'>Anh/Chị</option>
                    <option value='Ông'>Ông</option>
                    <option value='Bà'>Bà</option>
                    <option value='Khác'>Khác</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>Số điện thoại liên hệ</td>
            <td><input id="SDT" name="SDT" type="text" value="" /></td>
        </tr>     
        <tr>
            <td>Vacxin</td>
            <td>
                <select name="Vacxin" class="Vacxin" id="Vacxin">
                    <?php
                        foreach ($listvacxin as $item)
                        {
                            ?>
                                <option value='<?php echo $item->MaVacxin; ?>'>
                                    <?php echo $item->TenVacxin; ?> 
                                </option>
                            <?php
                        }
                    ?>
                </select>
            </td>
        </tr>   
        <tr>
            <td>Trung tâm VNVC</td>
            <td>
                <select name="TrungTam" class="TrungTam" id="MaDVVC">
                    <?php
                        foreach ($listcenter as $item)
                        {
                            ?>
                                <option value='<?php echo $item->MaTT; ?>'>
                                    <?php echo $item->TenTT; ?> 
                                </option>
                            <?php
                        }
                    ?>
                </select>
            </td>
        </tr>
        <tr>
            <td>Ngày tiêm</td>
            <td><input style="width:270px; height:30px;" id="NgayTiem" name="NgayTiem" type="date" value=""/></td>
        </tr>
    </table>
    <input type="submit" value="dangky" style="width: 200px; margin-left:250px; margin-top:20px;"/> 
    <br/><br/>
    <span id="message"> </span>
</form>
    