<?php
if (!function_exists('currency_format')) {
    function currency_format($number, $suffix = 'đ') {
        if (!empty($number)) {
            return number_format($number, 0, ',', '.') . "{$suffix}";
        }
    }
}
?>

<h3>GÓI VACXIN TRẺ EM TẠI TRUNG TÂM VNVC</h3>
<hr>

<form method="get" onsubmit="return check();">
    Gói vacxin: 
    <select name="MaGoi" class="combobox" id="combobox"  style="width:400px;">
        <?php
            foreach ($data as $item)
            {
                ?>
                    <option value='<?php echo $item->MaGoi; ?>'>
                        <?php echo $item->TenGoi; ?> 
                    </option>
                <?php
            }
        ?>
    </select>
    
    &ensp;
    <input type="submit" value="XemDSVacxin" style="width: 100px;"/>
    <input type="hidden" name="action" value="XemDSVacxin"/> &ensp;
    <span id="message"> </span>
</form>
<br/><br/>
<h3>GÓI VACXIN <?php if ($goivacxin) echo $goivacxin->TenGoi; else echo ""; ?></h3>
<hr/>
<p>Tổng giá gói với thời gian tiêm 12 tháng: <i style="color: red; font-weight: bold;"><?php if ($goivacxin) echo currency_format($goivacxin->TongGiaGoi_12); else echo "";?> </i></p>
<p>Tổng giá gói với thời gian tiêm 24 tháng: <i style="color: red; font-weight: bold;"><?php if ($goivacxin) echo currency_format($goivacxin->TongGiaGoi_24); else echo "";?> </i></p>

<form>
<div>
    <table class="empty-table">
        <thead>
            <tr>
                <th>Tên Vacxin</th>
                <th>Nước Sản Xuất</th>
                <th>Giá bán lẻ</th>
                <th>Số mũi/12 tháng</th>
                <th>Số mũi/24 tháng</th>
                <th>Nhóm bệnh</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <!-- PHẦN XỬ LÝ -->
        <?php
            if ($listvacxin)
            {
                // Tổng số record
                $total_records = count($listvacxin);

                // Tìm limit và current page
                $limit = 10;
                $current_page = isset($_GET['page']) ? $_GET['page'] : 1;

                //  Tổng pages
                $total_page = ceil($total_records / $limit);

                // Giới hạn current_page trong khoảng 1 đến total_page
                if ($current_page > $total_page){
                    $current_page = $total_page;
                }
                else if ($current_page < 1){
                    $current_page = 1;
                }

                // Tìm Start
                $start = ($current_page - 1) * $limit;

                if ($total_records - $start > 10)
                    $limit = $start + 10;
                else
                    $limit = $total_records;

                // 
                $result = array();
                for ($i = $start; $i < $limit; $i++)
                {
                    $v = new VacxinOfGoiVacxinModel();
                    $v = $listvacxin[$i];
                    $result[] = $v;
                }
            }
            else
                $result = null;
        ?>
        <!-- PHẦN HIỂN THỊ -->
        <?php
            if ($result && count($result) > 0) 
            {
                $sn=1;
                foreach ($result as $item) 
                {
                    ?>
                        <tr>
                            <td><?php echo $item->TenVacxin; ?></td>
                            <td><?php echo $item->NuocSanXuat; ?></td>
                            <td><?php echo currency_format($item->GiaBanLe); ?></td>
                            <td><?php echo $item->SoMui_12; ?></td>
                            <td><?php echo $item->SoMui_24; ?></td>
                            <td><?php echo $item->TenNhomBenh; ?></td>
                            <td>
                                <a href="?action=chitietvacxin&mavacxin=<?php echo $item->MaVacxin; ?>">Xem chi tiết Vacxin</a> &emsp;
                            </td>
                        <tr>

                    <?php
                }
            } 
            else { ?>
                        <tr>
                            <td colspan="8">No data found</td>
                        </tr>
                    <?php
                } 
        ?>
        </tbody>
    </table>
    <br/>
    <!-- PHẦN PHÂN TRANG -->
    <div class="paging">
        <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // HIỂN THỊ PHÂN TRANG
            if ($result)
            {
                echo '<a href="?MaGoi='.($goivacxin->MaGoi).'&action=XemDSVacxin&page=1" style="width:50px; display:inline-block">First</a> | ';

                // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
                if ($current_page > 1 && $total_page > 1)
                {
                    echo '<a href="?MaGoi='.($goivacxin->MaGoi).'&action=XemDSVacxin&page='.($current_page-1).'" style="width:50px; display:inline-block">Prev</a> | ';
                }
    
                
                // Lặp khoảng giữa
                for ($i = 1; $i <= $total_page; $i++)
                {
                    // Nếu là trang hiện tại thì hiển thị thẻ span
                    // ngược lại hiển thị thẻ a
                    if ($i == $current_page)
                    {
                        echo '<span style="width:50px; display:inline-block">'.$i.'</span> | ';
                    }
                    else{
                        echo '<a href="?MaGoi='.($goivacxin->MaGoi).'&action=XemDSVacxin&page='.$i.'" style="width:50px; display:inline-block">'.$i.'</a> | ';
                    }
                }
    
                // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
                if ($current_page < $total_page && $total_page > 1)
                {
                    echo '<a href="?MaGoi='.($goivacxin->MaGoi).'&action=XemDSVacxin&page='.($current_page+1).'" style="width:50px; display:inline-block">Next</a> | ';
                }

                echo '<a href="?MaGoi='.($goivacxin->MaGoi).'&action=XemDSVacxin&page='.($total_page).'" style="width:50px; display:inline-block">Last</a> | ';
            }
        ?>
    </div>
</div>
</form>





