<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript">
    function CheckAll(parent)
    {
        var ids = document.getElementsByTagName('input');
        for(var i=0; i<ids.length; i++)
        {
            if(ids[i].name == "checkbox[]")
            {
                ids[i].checked = parent.checked;
            }
	    }
    }

    function check()
    {
        var n = document.getElementById("Number").value;
        var regex=/^[0-9]+$/;
        
        if (n == "" || n.match(regex))
        {
            return true;
        }
        else
        {
            document.getElementById("message").innerHTML = "<i><b style='color:red'>Number là \"số\" !</b></i>";
            return false;
        }
    }
</script>

<h3>Tìm kiếm cầu thủ</h3>

<form action="Index.php" method="get" onsubmit="return check();">
    Họ tên: <input type="text" name="keyword" style="width: 150px;"/>&ensp;
    Số áo:  <input id="Number" type="text" name="number" style="width: 80px;"/>&ensp;
    Quốc tịch: <input type="text" name="nationality" style="width: 120px;"/>
    &emsp;
    <input type="submit" value="search" style="width: 100px;"/>
    <input type="hidden" name="action" value="search"/> &ensp;
    <span id="message"> </span>
</form>


<div class="custom-select" style="width:200px;">
    
</div>
<br/>
<form method="POST" >
<input type="hidden" name="action" value="deleteAllPlayerCheckedBox" />
<div>
    <table class="empty-table">
        <thead>
            <tr>
                <th>
                    <input name="allbox" type="checkbox" id="allbox" value="All" onclick="CheckAll(this)"/>
                    <i>CheckAll</i>>
                </th>
                <th>PlayerID</th>
                <th>FullName</th>
                <th>ClubID</th>
                <th>DOB</th>
                <th>Position</th>
                <th>Nationality</th>
                <th>Number</th>
                <th></th>
            </tr>
        </thead>
        <tbody id="databody">
        <!-- PHẦN XỬ LÝ -->
        <?php
            // Tổng số record
            $total_records = count($datasearch);

            // Tìm limit và current page
            $limit = 10;
            $current_page = isset($_GET['page']) ? $_GET['page'] : 1;

            //  Tổng pages
            $total_page = ceil($total_records / $limit);

            // Giới hạn current_page trong khoảng 1 đến total_page
            if ($current_page > $total_page){
                $current_page = $total_page;
            }
            else if ($current_page < 1){
                $current_page = 1;
            }

            // Tìm Start
            $start = ($current_page - 1) * $limit;

          
            if ($total_records - $start > 10)
                $limit = $start + 10;
            else
                $limit = $total_records;


            // 
            $result = array();
            for ($i = $start; $i < $limit; $i++)
            {
                $player = new PlayerModel();
                $player = $datasearch[$i];
                $result[] = $player;
            }
        ?>
        <!-- PHẦN HIỂN THỊ -->
        <?php
            if (count($result) > 0) 
            {
                $i = 1;

                foreach ($result as $item) 
                {
                    ?>
                        <tr>
                            <td>
                                <input id="checkbox" name="checkbox[]" type="checkbox" value='<?php echo $item->PlayerID; ?>'/>    
                            </td>
                            <td><?php echo $item->PlayerID; ?></td>
                            <td><?php echo $item->FullName; ?></td>
                            <td><?php echo $item->ClubID; ?></td>
                            <td><?php echo $item->DOB; ?></td>
                            <td><?php echo $item->Position; ?></td>
                            <td><?php echo $item->Nationality; ?></td>
                            <td><?php echo $item->Number; ?></td>
                            <td> 
                                <a href='?action=deleteplayer&PlayerID=<?php echo $item->PlayerID; ?>'>Xoá</a> &emsp;
                                <a href='?action=updateplayer&PlayerID=<?php echo $item->PlayerID; ?>'>Cập nhật</a>
                            </td>
                        <tr>

                    <?php
                    $i++;
                }
            } 
            else { ?>
                        <tr>
                            <td colspan="8">No data found</td>
                        </tr>
                    <?php
                }
        ?>
        </tbody>

    </table>
    <br/>
    <!-- PHẦN PHÂN TRANG -->
    <div class="paging">
        <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // HIỂN THỊ PHÂN TRANG
            
            echo '<a href="?keyword='.($keyword).'&number='.($number).'&nationality='.($nationality).'&action=search&page=1" style="width:50px; display:inline-block">First</a> | ';
            
            // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
            if ($current_page > 1 && $total_page > 1)
            {
                echo '<a href="?keyword='.($keyword).'&number='.($number).'&nationality='.($nationality).'&action=search&page='.($current_page-1).'" style="width:50px; display:inline-block">Prev</a> | ';
            }
 
            
            // Lặp khoảng giữa
            for ($i = $current_page; $i <= $current_page + 1; $i++)
            {
                // Nếu là trang hiện tại thì hiển thị thẻ span
                // ngược lại hiển thị thẻ a
                if ($i == $current_page)
                {
                    echo '<span style="width:50px; display:inline-block">'.$i.'</span> | ';
                }
                else{
                    echo '<a href="?keyword='.($keyword).'&number='.($number).'&nationality='.($nationality).'&action=search&page='.$i.'" style="width:50px; display:inline-block">'.$i.'</a> | ';
                }
            }
            

            
 
            // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
            if ($current_page < $total_page && $total_page > 1)
            {
                echo '<a href="?keyword='.($keyword).'&number='.($number).'&nationality='.($nationality).'&action=search&page='.($current_page+1).'" style="width:50px; display:inline-block">Next</a> | ';
            }

            echo '<a href="?keyword='.($keyword).'&number='.($number).'&nationality='.($nationality).'&action=search&page='.($total_page).'" style="width:50px; display:inline-block">Last</a> | ';
        ?>
    </div>
    <input type="submit" value="deleteAllPlayerCheckedBox" style="width: 200px;" />
</div>
</form>
