

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript">
  
</script>

<h3>TÌM TRUNG TÂM VNVC</h3>

<form method="get" onsubmit="return check();">
    Tỉnh / thành phố: 
    <select name="TinhThanh" class="combobox" id="combobox"  >
        <option value='All' selected>All</option>
        <?php
            foreach ($tt as $item)
            {
                ?>
                    <option value='<?php echo $item; ?>'>
                        <?php echo $item; ?> 
                    </option>
                <?php
            }
        ?>
    </select>
    
    &ensp;
    <input type="submit" value="timtrungtam" style="width: 100px;"/>
    <input type="hidden" name="action" value="timtrungtam"/> &ensp;
    <span id="message"> </span>
</form>
<br/><br/><hr/><br/>

<form>
<div>
    <table class="empty-table">
        <thead>
            <tr>
                <th>Mã</th>
                <th>Tên trung tâm</th>
                <th>SDT</th>
                <th>Tỉnh thành</th>
                <th>Quận huyện</th>
                <th>Phường xã</th>
                <th>Số nhà</th>
            </tr>
        </thead>
        <tbody>
        <!-- PHẦN XỬ LÝ -->
        <?php
            // Tổng số record
            $total_records = count($data);

            // Tìm limit và current page
            $limit = 9;
            $current_page = isset($_GET['page']) ? $_GET['page'] : 1;

            //  Tổng pages
            $total_page = ceil($total_records / $limit);

            // Giới hạn current_page trong khoảng 1 đến total_page
            if ($current_page > $total_page){
                $current_page = $total_page;
            }
            else if ($current_page < 1){
                $current_page = 1;
            }

            // Tìm Start
            $start = ($current_page - 1) * $limit;

            if ($total_records - $start > 9)
                $limit = $start + 9;
            else
                $limit = $total_records;

            // 
            $result = array();
            for ($i = $start; $i < $limit; $i++)
            {
                $club = new TrungTamModel();
                $club = $data[$i];
                $result[] = $club;
            }
        ?>
        <!-- PHẦN HIỂN THỊ -->
        <?php
            if (count($result) > 0) 
            {
                $sn=1;
                foreach ($result as $item) 
                {
                    ?>
                        <tr>
                            <td><?php echo $item->MaTT; ?></td>
                            <td><?php echo $item->TenTT; ?></td>
                            <td><?php echo $item->SDT; ?></td>
                            <td><?php echo $item->TinhThanh; ?></td>
                            <td><?php echo $item->QuanHuyen; ?></td>
                            <td><?php echo $item->PhuongXa; ?></td>
                            <td><?php echo $item->SoNha; ?></td>
                        <tr>

                    <?php
                }
            } 
            else { ?>
                        <tr>
                            <td colspan="8">No data found</td>
                        </tr>
                    <?php
                } 
        ?>
        </tbody>
    </table>
    <br/>
    <!-- PHẦN PHÂN TRANG -->
    <div class="paging">
        <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // HIỂN THỊ PHÂN TRANG
 
            echo '<a href="?action=timtrungtam&page=1" style="width:50px; display:inline-block">First</a> | ';

            // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
            if ($current_page > 1 && $total_page > 1)
            {
                echo '<a href="?action=timtrungtam&page='.($current_page-1).'" style="width:50px; display:inline-block">Prev</a> | ';
            }
 
            // Lặp khoảng giữa
            for ($i = 1; $i <= $total_page; $i++)
            {
                // Nếu là trang hiện tại thì hiển thị thẻ span
                // ngược lại hiển thị thẻ a
                if ($i == $current_page)
                {
                    echo '<span style="width:50px; display:inline-block">'.$i.'</span> | ';
                }
                else{
                    echo '<a href="?action=timtrungtam&page='.$i.'" style="width:50px; display:inline-block">'.$i.'</a> | ';
                }
            }
 
            // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
            if ($current_page < $total_page && $total_page > 1)
            {
                echo '<a href="?action=timtrungtam&page='.($current_page+1).'" style="width:50px; display:inline-block">Next</a> | ';
            }

            echo '<a href="?action=timtrungtam&page='.($total_page).'" style="width:50px; display:inline-block">Last</a> | ';
        ?>
    </div>
</div>
</form> 