<h3>TƯ VẤN</h3>
<hr/>
<form>
<div>
    <table class="empty-table">
        <thead>
            <tr>
                <th style="width: 100px;">Họ tên</th>
                <th style="width: 70px;">Địa chỉ</th>
                <th style="width: 50px;">Email</th>
                <th style="width: 30px;">Giới tính</th>
                <th style="width: 40px;">SDT</th>
                <th style="width: 20px;">Tuổi</th>
                <th style="width: 80px;">Loại câu hỏi</th>
                <th style="width: 220px;">Nội dung</th>
                <th>Thời gian</th>
            </tr>
        </thead>
        <tbody>
        <!-- PHẦN XỬ LÝ -->
        <?php
            // Tổng số record
            $total_records = count($data);

            // Tìm limit và current page
            $limit = 3;
            $current_page = isset($_GET['page']) ? $_GET['page'] : 1;

            //  Tổng pages
            $total_page = ceil($total_records / $limit);

            // Giới hạn current_page trong khoảng 1 đến total_page
            if ($current_page > $total_page){
                $current_page = $total_page;
            }
            else if ($current_page < 1){
                $current_page = 1;
            }

            // Tìm Start
            $start = ($current_page - 1) * $limit;

            if ($total_records - $start > 3)
                $limit = $start + 3;
            else
                $limit = $total_records;

            // 
            $result = array();
            for ($i = $start; $i < $limit; $i++)
            {
                $v = new TuVanModel();
                $v = $data[$i];
                $result[] = $v;
            }
        ?>
        <!-- PHẦN HIỂN THỊ -->
        <?php
            if (count($result) > 0) 
            {
                $sn=1;
                foreach ($result as $item) 
                {
                    ?>
                        <tr>
                            <td><?php echo $item->HoTen; ?></td>
                            <td><?php echo $item->DiaChi; ?></td>
                            <td><?php echo $item->Email; ?></td>
                            <td><?php echo $item->GioiTinh; ?></td>
                            <td><?php echo $item->SDT; ?></td>
                            <td><?php echo $item->Tuoi; ?></td>
                            <td><?php echo $item->LoaiCauHoi; ?></td>
                            <td><?php echo $item->NoiDung; ?></td>
                            <td><?php echo $item->ThoiGian; ?></td>
                        <tr>

                    <?php
                }
            } 
            else { ?>
                        <tr>
                            <td colspan="8">No data found</td>
                        </tr>
                    <?php
                } 
        ?>
        </tbody>
    </table>
    <br/>
    <!-- PHẦN PHÂN TRANG -->
    <div class="paging">
        <?php 
            // PHẦN HIỂN THỊ PHÂN TRANG
            // HIỂN THỊ PHÂN TRANG
 
            echo '<a href="?action=tuvan&page=1" style="width:50px; display:inline-block">First</a> | ';

            // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
            if ($current_page > 1 && $total_page > 1)
            {
                echo '<a href="?action=tuvan&page='.($current_page-1).'" style="width:50px; display:inline-block">Prev</a> | ';
            }
 
            // Lặp khoảng giữa
            for ($i = 1; $i <= $total_page; $i++)
            {
                // Nếu là trang hiện tại thì hiển thị thẻ span
                // ngược lại hiển thị thẻ a
                if ($i == $current_page)
                {
                    echo '<span style="width:50px; display:inline-block">'.$i.'</span> | ';
                }
                else{
                    echo '<a href="?action=tuvan&page='.$i.'" style="width:50px; display:inline-block">'.$i.'</a> | ';
                }
            }
 
            // nếu current_page < $total_page và total_page > 1 mới hiển thị nút prev
            if ($current_page < $total_page && $total_page > 1)
            {
                echo '<a href="?action=tuvan&page='.($current_page+1).'" style="width:50px; display:inline-block">Next</a> | ';
            }

            echo '<a href="?action=tuvan&page='.($total_page).'" style="width:50px; display:inline-block">Last</a> | ';
        ?>
    </div>
</div>
</form>
<h3>THÊM CÂU HỎI</h3>
<hr/>
<form method ="POST" onsubmit="return check();">
 	<input type="hidden" name="action" value="guicauhoi" />
    <table>
        <tr>
            <td>Mã TV: </td>
            <td><input id="MaTV" name="MaTV" type="text" value="" /></td>
        </tr>
        <tr>
            <td>Họ tên:</td>
            <td><input id="HoTen" name="HoTen" type="text" value=""/></td>                   
        </tr>
        <tr>
            <td>Địa chỉ:</td>
            <td><input id="DiaChi" name="DiaChi" type="text" value=""/></td>                   
        </tr>
        <tr>
            <td>Email:</td>
            <td><input id="Email" name="Email" type="text" value=""/></td>                   
        </tr>
        <tr>
            <td>Giới tính:</td>
            <td>
                <select name="GioiTinh" class="GioiTinh" id="GioiTinh">
                    <option value='Nam'>Nam</option>
                    <option value='Nữ'>Nữ</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>Số điện thoại:</td>
            <td><input id="SDT" name="SDT" type="text" value="" /></td>
        </tr>   
        <tr>
            <td>Tuổi:</td>
            <td><input id="Tuoi" name="Tuoi" type="text" value="" /></td>
        </tr>  
        <tr>
            <td>Loại câu hỏi:</td>
            <td><input id="LoaiCauHoi" name="LoaiCauHoi" type="text" value="" /></td>
        </tr>
        <tr>
            <td>Nội dung:</td>
            <td><input style="width:275px; height:60px; word-break:break-all; word-wrap: break-word;" id="NoiDung" name="NoiDung" type="text" value="" /></td>
        </tr>     
    </table>
    <input type="submit" value="guicauhoi" style="width: 200px; margin-left:180px; margin-top:7px;"/> 
    <span id="message"> </span>
</form>