<div class="sidebox">
    <h2>Giới thiệu</h2>
    <div class="vmenu">
        <ul>
            <li>
                18120553 - Nguyễn Lê Ngọc Tần 
            </li>
            <li>
                18120560 - Lê Hữu Thanh
            </li>
            <li>
                18120570 - Nguyễn Thanh Thi
            </li>
            <li>
                18120590 - Lê Việt Tiến
            </li>
        </ul>
    </div>

</div>

<div class="sidebox">    
    <h2>Danh sách chức năng</h2>
    <div class="vmenu">
        <ul>
            <li>
                <a href="index.php"> <b> Trang chủ </b> </a>
            </li>
            <li>
                <a href="?action=banggia">Bảng giá Vacxin</a>
            </li>            
            <li>
                <a href="?action=dangkytiem">Đăng ký tiêm</a>
            </li>
            <li>
                <a href="?action=datmua">Đặt mua Vacxin</a>
            </li>
            <li>
                <a href="?action=vacxintreem">Gói Vacxin cho trẻ em</a>
            </li>
            <li>
                <a href="?action=timtrungtam">Tìm trung tâm VNVC</a>
            </li>
            <li>
                <a href="?action=tuvan">Tư vấn</a>
            </li>
        </ul>
    </div>
</div>