<!DOCTYPE html>
<html>
    <head>
        <title id="title"> Trung tâm VNVC </title>
        <?php require("include/meta.phtml"); ?>     
    </head>
    <body>
        <div id="header"></div>
        <div id="body">
            <div id="topbar">
                <div id="header-text"> <h1> V N V C - V i e t n a m  V a c x i n  J S C </h1> </div>
            </div>              
            <div id="wrapper">   
                <div id="smallbar"></div> 
                <div id="content" style="height: 800px;">    
                    <!-- ------------------------------------ -->
                    <!-- ------------------------------------ -->
                    <!-- BEGIN: Nội dung chính của trang web  -->
                    <div id="primary" style="height: 800px;">                    
                        <?php require($VIEW); ?>
                    </div>
                    <!-- END: Nội dung chính của trang web  -->
                    <!-- ------------------------------------ -->
                    <!-- ------------------------------------ -->
                    <div id="secondary" style="height: 800px;">
                        <?php require("include/secondary.phtml"); ?>                    
                    </div>
                </div>    
                <div id="smallbar"></div>        
                <div id="footer">
                    <image id="logo" src="./css/images/logo.png" />
                    <div id="footer-text">
                        <b> Copyright: Đồ án Quản trị CSDL HD </b> <br/>
                        2021 - 2022
                    </div>
                </div>
            </div>      
        </div> 
           
    </body>
</html>
